create table tb_cidade (id int8 generated by default as identity, cidade_c varchar(255), uf_c varchar(255), primary key (id));
create table tb_roteiro (id int8 generated by default as identity, cidade_c int8, modelo_v int8, poltrona_v int8, primary key (id));
create table tb_usuario (id int8 generated by default as identity, cargo_u varchar(255), email_u varchar(255), login_u varchar(255), nome_u varchar(255), senha_u varchar(255), primary key (id));
create table tb_veiculo (id int8 generated by default as identity, data_compra_v date, modelo_v varchar(255), motorista_v varchar(255), placa_v varchar(255), poltrona_v int4, primary key (id));
