create table tb_cidade (id int8 generated by default as identity, cidade_c varchar(255), uf_c varchar(255), primary key (id));
create table tb_roteiro (id int8 generated by default as identity, cidade_c int8, modelo_v int8, poltrona_v int8, primary key (id));
create table tb_usuario (id int8 generated by default as identity, cargo_u varchar(255), email_u varchar(255), login_u varchar(255), nome_u varchar(255), senha_u varchar(255), primary key (id));
create table tb_veiculo (id int8 generated by default as identity, data_compra_v date, modelo_v varchar(255), motorista_v varchar(255), placa_v varchar(255), poltrona_v int4, primary key (id));
alter table if exists tb_roteiro add constraint FKrcjugmpnelib46131hncc3hdj foreign key (cidade_c) references tb_cidade;
alter table if exists tb_roteiro add constraint FKepo2lg2ln6uvq1lollrw1i4ea foreign key (modelo_v) references tb_veiculo;
alter table if exists tb_roteiro add constraint FKde900d1g8l9i74qarx1qu95u3 foreign key (poltrona_v) references tb_veiculo;
